### ISSUE TITLE
format of dataset

### ISSUE THREAD

**Issue by shworldns** [drboog/Lafite#17]
It seems that the format of the dataset you provided is wrong

**Comment by drboog** [comment]
Can you post a screenshot of error? And describe which dataset you are using, what running script you are using.
Otherwise I do not know what could be the reason for the problem you are facing, because these datasets are what I used previously, and other people use this repo haven't reported any similar problem with datasets, so I have no clue now.

**Comment by drboog** [comment]
The zip file datasets I provided are already pre-processed, you don't need to process them any further.

**Comment by shworldns** [comment]
> The zip file datasets I provided are already pre-processed, you don't need to process them any further.

Thank you very much for your reply！Maybe I misunderstand, I thought the format of the zip file is that each image corresponds to a text file. Thanks again for your reply!

**Comment by drboog** [comment]
You're welcome, that dataset_tool.py is used for creating your own dataset.
