### ISSUE TITLE
Intuition of injecting noises for pseudo text features 

### ISSUE THREAD

**Issue by kminsoo** [drboog/Lafite#18]
Hi authors, 

I really appreciate you for sharing your codes. 
I would like to ask a question about the intuition of injecting the random noise instead of using the image feature embedded by CLIP.

Thank you in advance!

**Comment by drboog** [comment]
Hi, in language-free setting, we inject perturbated (noised) CLIP image features, not random noises or un-noised image features.
The first reason is very simple, because this will lead to better results. 
The second reason is related to CLIP itself, we add noises to CLIP image features to construct pseudo CLIP text features because image and text features are NOT well-aligned actually. Say image-text pairs have similarity A (A< 1) in the joint feature space, to make sure our constructed pseudo text features have similarity A with ground-truth image features, the straight-forward way is to perturb it. In other words, if image-text pairs always have similarity 1.0, then we do not need to use any perturbation, we can directly use image features as pseudo text features.

**Comment by kminsoo** [comment]
Thank you for answering my question.
However, I empirically observe that the cosine similarity between the pseudo (fixed perturbation) and ground truth text feature is less than the one between the clip image and ground truth text feature, which implies that the clip image feature locates closer to the ground-truth text feature compared to the proposed pseudo text feature. 
Based on the observation, do you have any intuitive ideas about why pseudo text features of LAFITE performs better than the naive clip image feature?

**Comment by drboog** [comment]
Yes, if you directly look at the cosine similarity with ground-truth image features, seems directly using ground-truth image features are better,  but it obtains worse empirical results, because the cosine similarity can actually be misleading. 
Let's denote the set of all ground-truth image features as _**I**_, all ground-truth text features as **_T_**, all pseudo text features as **_P_**. Since **_P_** is obtained by adding noises to the elements in _**I**_, thus **_P_** is a larger region than **_I_**. 
The ground-truth image  features and text features are not well aligned in the joint features space, they are two small regions of the whole space, and they are likely disjoint (no overlapping between _**T**_ and _**I**_). This means if you train a model on image features (**_I_**) and test it on text features (**_T_**), the data (features) during training and testing are quite different.
What Lafite does is actually construct a _**P**_  based on **_I_**, so that it is large enough (by tuning the noise level) to have overlapping with _**T**_,  e.g. make _**T**_  become a subset of _**P**_. Although on average pseudo text features will have smaller cosine similarity, we have less data (feature) gap between training and testing, which leads to better performance.

**Comment by kminsoo** [comment]
That makes sense that pseudo text feature leads to reduce the gap, which leads to increase the visual quality. 
I wonder the smaller cosine similarity problem also incurs to generate images which is less relevant to given text sentences.
