### ISSUE TITLE
A Question on Injecting Text Condition into Each Generator Layer. 

### ISSUE THREAD

**Issue by yaoyiran** [drboog/Lafite#28]
Hi, I found that there seems to be a discrepancy between the paper's figure 3 (also the related descriptions on Section 3.2) and the code. Could you help to verify if my understanding is correct? Thanks a lot! Of course, the discrepancy is not an error and does not influence any correctness at all. I am just currently developing a TTI work based on LAFITE and hope to be more clear about the details.

In LAFITE paper's fig 3, there are two types of affine mappings: (1) mapping W to S (2) mapping the concatenation of [S,C] to U. 
<img width="542" alt="Screenshot 2022-12-11 at 21 00 51" src="https://user-images.githubusercontent.com/25559589/206917829-a6f1ce66-c06e-46d0-8225-2d03cc122cd3.png">

However, in the network.py [[L454-L457]](https://github.com/drboog/Lafite/blob/main/training/networks.py#L454-L457), there is only one affine mapping. Actually it simply concatenates W (rather than S) with C and an affine mapping maps it to U directly.

**Comment by drboog** [comment]
Affine **transformations** are operations without activation function/non-linearity. 
https://mathworld.wolfram.com/AffineTransformation.html
Assume A, B, C, D are matrices, b c d are vectors, where D=BC, d=bC+c. Then (AB+b)C +c= ABC+bC+c = AD+d, isn't it? 
Then you can understand that the implementation is consistent with the figure, because no non-linear function is used here.

PS: I know some people consider affine **layer** as a composition of affine transformation and activation function, while some people consider it as simple affine transformation. So I try to not use the term **affine layer**, but use term **affine transformation** (for operation without activation) and **fully-connected layers** (for operation with activation) instead.

**Comment by yaoyiran** [comment]
Cool, thanks! I see, they are identical.
