### ISSUE TITLE
Tune hyperparameters

### ISSUE THREAD

**Issue by hari1106** [drboog/Lafite#30]
Hi,
Thanks for sharing this wonderful work. Could you please explain how to tune itd, itc and gamma for custom dataset.
Thanks in advance

**Comment by drboog** [comment]
Hi,
When itd and itc is too small, clip supervision is too weak. But when clip supervision is too strong, it may lead to bad image quality.
Large gamma can lead to quick decrease of FID at the beginning of training, but it may lead to unsatisfactory result after finishing training because the regularization may be too strong.
So I would suggest starting with itd=0, itc=0, gamma=10. Then try larger itd and itc (0.1, 1, 5, 10) and smaller gamma (5, 2, 1, 0.1) until you find the best results.
