### ISSUE TITLE
Question about finetuning hyperparams for mscoco

### ISSUE THREAD

**Issue by elaine-sui** [drboog/Lafite#32]
Hi,
I was wondering what hyperparameters you used for finetuning the pre-trained CC3M model on MSCOCO (language-free gaussian) and how many kimgs was it finetuned for? Also, I'm starting to finetune the model myself and it seems to take very long. I'm only using one GPU but it takes roughly 3 hours for 50 ticks. Is that expected?

Thanks!

**Comment by drboog** [comment]
Hi, 
I used gamma=10, itc=itd=10 I think. 
I think fine-tuning our pre-trained CC3M model on MS-COCO leads to worse results than directly training from scratch on MS-COCO (see Table 4 in the paper). If you are looking for good results with this codebase, I think directly training on MS-COCO might be better.
But if you try to get a model on MM-CelebA-HQ, fine-tuning a model pre-trained on FFHQ will lead to better results than training from scratch. So it is dataset-dependent.
If you are using one GPU, I think it may take some time. I think training on 4 GPUs for 25000kimgs may take 3 days (time could be very different on different GPUs ).

**Comment by victorup** [comment]
Hi, 
I tried to fine-tune the model on the COCO dataset and tried adjusting many hyperparameters to improve performance. However, the results of the test images are still a bit blurry. There is an issue with the image below. What do you think could be causing this problem? Do you have any suggestions?
<img width="256" alt="image" src="https://user-images.githubusercontent.com/44796817/232972972-061124c3-f823-4917-a0e8-9881f28e4c56.png">

**Comment by drboog** [comment]
> Hi, I tried to fine-tune the model on the COCO dataset and tried adjusting many hyperparameters to improve performance. However, the results of the test images are still a bit blurry. There is an issue with the image below. What do you think could be causing this problem? Do you have any suggestions? <img alt="image" width="256" src="https://user-images.githubusercontent.com/44796817/232972972-061124c3-f823-4917-a0e8-9881f28e4c56.png">

If you are using Lafite, finetuning pre-trained CC3M model on MS-COCO would lead to much worse results than directly training on MS-COCO. This happens because of the difficulty in GAN training and the dataset gap between CC3M and MS-COCO. Also, if you fine-tune it in a language-free manner, results could be even worse because some of the patterns that the model learned will be distorted.

Unless you are trying to propose a new language-free method and only use Lafite as a baseline method, I would suggest you not fine-tune pre-trained CC3M model, especially if you are looking for some good generation. Even if you just use Lafite as a baseline method, training from scratch on MS-COCO is suggested.
